server:
  port: 10011
spring:
  application:
    name: xuaian-zuul
zuul:
  routes:
    xuxian-article: /user-article/** #\u7B80\u5199
    xuxian-base: /xuxian-base/**
    xuxian-sms: /xuxian-sms/**
    xuxian-user: /xuaian-user/**
    #path: /user-service/**
    #serviceId: user-service

    #url: http://127.0.0.1:8082
    #127.0.0.1:10011/user-service/user/getUserById/3
  #prefix: /api

eureka:
  client:
    service-url: #\u6CE8\u518C\u5230eureka\u6CE8\u518C\u4E2D\u5FC3
      defaultZone: http://127.0.0.1:8888/eureka/


