server:
  port: 8085
spring:
  application:
    name: xuxian-sms
  rabbitmq:
    username: root
    password: 111
    host: 192.168.147.132
aliyun:
  sms:
    accessKeyId: LTAI4GChy5VPqLJ3DoTARxKc
    accessSecret: jjxyyCp10VXKt6BjNpM42Nw8anGgMb
    signName: imisbest
    templateCode: SMS_179610113