server:
  port: 8082
spring:
  application:
    name: xuxian-article

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.147.132:3306/xuxian-article?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatement=true
    username: root
    password: root

  jpa:
    show-sql: true
    database: mysql
  redis:
    host: 192.168.147.132
eureka:
  client:
    service-url: #注册到eureka注册中心
      defaultZone: http://127.0.0.1:8888/eureka/
feign:
  hystrix:
    enabled: true
